import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {McLaren,Cinzel} from 'next/font/google'


const mc = McLaren({ 
  subsets: ['latin'], 
  weight: '400', 
  variable:'--font-McLaren' })
  
const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cinzel",
});

import Navbar from "./home/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={mc.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#EDE0BE] pt-20`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
